/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sohu_focus_libandfix_AndFix */

#ifndef _Included_com_sohu_focus_libandfix_AndFix
#define _Included_com_sohu_focus_libandfix_AndFix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sohu_focus_libandfix_AndFix
 * Method:    setup
 * Signature: (ZI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sohu_focus_libandfix_AndFix_setup
  (JNIEnv *, jclass, jboolean, jint);

/*
 * Class:     com_sohu_focus_libandfix_AndFix
 * Method:    replaceMethod
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_com_sohu_focus_libandfix_AndFix_replaceMethod
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_sohu_focus_libandfix_AndFix
 * Method:    setFieldFlag
 * Signature: (Ljava/lang/reflect/Field;)V
 */
JNIEXPORT void JNICALL Java_com_sohu_focus_libandfix_AndFix_setFieldFlag
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
